# Generated by Django 5.0.2 on 2024-03-14 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserData', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdatamodule',
            name='biodata',
        ),
        migrations.AddField(
            model_name='userdatamodule',
            name='city',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='userdatamodule',
            name='email',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='userdatamodule',
            name='phonenumber',
            field=models.CharField(default='', max_length=10),
        ),
    ]
