# Generated by Django 5.0.2 on 2024-03-22 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserData', '0002_remove_userdatamodule_biodata_userdatamodule_city_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckUserStatusModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userStatus', models.BooleanField(default=False)),
            ],
        ),
    ]
