# Generated by Django 5.0.2 on 2024-03-23 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserData', '0003_checkuserstatusmodule'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLoggedInStateModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userStat', models.BooleanField(default=False)),
                ('username', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='CheckUserStatusModule',
        ),
    ]
