# Generated by Django 5.0.2 on 2024-03-24 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserData', '0004_userloggedinstatemodule_delete_checkuserstatusmodule'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userloggedinstatemodule',
            old_name='userStat',
            new_name='user_status',
        ),
    ]
