# Generated by Django 5.0.2 on 2024-03-28 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserData', '0005_rename_userstat_userloggedinstatemodule_user_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBankAccountsDataModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('acc_name', models.CharField(max_length=30)),
                ('acc_code', models.CharField(max_length=30)),
                ('currency', models.CharField(max_length=30)),
                ('acc_num', models.CharField(max_length=30)),
                ('bank_name', models.CharField(max_length=30)),
                ('ifsc', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='UserCardAccountsDataModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('acc_name', models.CharField(max_length=30)),
                ('acc_code', models.CharField(max_length=30)),
                ('currency', models.CharField(max_length=30)),
                ('bank_name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=500)),
            ],
        ),
    ]
