# Generated by Django 5.0.2 on 2024-03-29 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserData', '0006_userbankaccountsdatamodule_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbankaccountsdatamodule',
            name='balance',
            field=models.FloatField(default=0.0, max_length=30),
        ),
        migrations.AddField(
            model_name='usercardaccountsdatamodule',
            name='balance',
            field=models.FloatField(default=0.0, max_length=30),
        ),
    ]
