# Generated by Django 5.0.2 on 2024-03-30 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserData', '0008_usersalesorderlistmodule'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPurchaseOrderListModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('purchase_num', models.CharField(max_length=30)),
                ('purchase_date', models.DateField()),
                ('product_name', models.CharField(max_length=50)),
                ('product_quan', models.FloatField()),
                ('ship_date', models.DateField()),
                ('product_cost', models.FloatField()),
            ],
        ),
    ]
